In [1]:
import os, sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scanpy as sc
import torch

sys.path.append("./Tangram") 
import tangram as tg

## Convert spatial data

In [2]:
# slideseq coordinates
path = os.path.join('data', 'puck_coords.txt')
sp_coords = pd.read_csv(path, index_col=0)
sp_coords

                         x            y
barcode
TTCTCCAAGGCCG  1478.453901  1810.524823
TACTAAAGAATTA  2224.000000  1230.397849
TCTCTTAGTTGGC  1914.742424  2221.954545
GCTTTTCGTTCCC  1682.151515  3886.575758
TACGGGCGAAAAG  2416.261194  4216.902985
...                    ...          ...
CTACCGTGCGGCG  5176.223776  3567.398601
CCGATATGCGGCG  2222.324324  3906.189189
TTGGTATCGCCGC  3187.536082  2031.268041
TTCTTATCGCCGC  3686.817460  3833.047619
TTGTCGTATAGCG  4084.235294  1917.862745

[27261 rows x 2 columns]

In [3]:
# slideseq counts
path = os.path.join('data', 'puck_counts.txt')
sp_counts = pd.read_csv(path, index_col=0)
sp_counts

,0610007P14Rik,0610009B22Rik,0610009E02Rik,0610009L18Rik,0610009O20Rik,0610010F05Rik,0610010K14Rik,0610011F06Rik,0610030E20Rik,0610037L13Rik,...,mt-Tl1,mt-Tl2,mt-Tm,mt-Tp,mt-Tq,mt-Tr,mt-Ts2,mt-Tt,mt-Tv,n-R5-8s1
barcode,,,,,,,,,,,,,,,,,,,,,
TTCTCCAAGGCCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TACTAAAGAATTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCTCTTAGTTGGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCTTTTCGTTCCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TACGGGCGAAAAG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTACCGTGCGGCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCGATATGCGGCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTGGTATCGCCGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTCTTATCGCCGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTGTCGTATAGCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# make sure the index are in the same order
assert sp_coords.index.equals(sp_counts.index)

In [6]:
# convert to spatial anndata
ad_sp = sc.AnnData(sp_counts)
ad_sp.obs['x'] = sp_coords.x
ad_sp.obs['y'] = sp_coords.y
ad_sp

AnnData object with n_obs Ã— n_vars = 27261 Ã— 17919
    obs: 'x', 'y'

In [7]:
ad_sp.obs

                         x            y
barcode
TTCTCCAAGGCCG  1478.453901  1810.524823
TACTAAAGAATTA  2224.000000  1230.397849
TCTCTTAGTTGGC  1914.742424  2221.954545
GCTTTTCGTTCCC  1682.151515  3886.575758
TACGGGCGAAAAG  2416.261194  4216.902985
...                    ...          ...
CTACCGTGCGGCG  5176.223776  3567.398601
CCGATATGCGGCG  2222.324324  3906.189189
TTGGTATCGCCGC  3187.536082  2031.268041
TTCTTATCGCCGC  3686.817460  3833.047619
TTGTCGTATAGCG  4084.235294  1917.862745

[27261 rows x 2 columns]

In [8]:
ad_sp.var

Empty DataFrame
Columns: []
Index: [0610007P14Rik, 0610009B22Rik, 0610009E02Rik, 0610009L18Rik, 0610009O20Rik, 0610010F05Rik, 0610010K14Rik, 0610011F06Rik, 0610030E20Rik, 0610037L13Rik, 0610038B21Rik, 0610039K10Rik, 0610040B10Rik, 0610040F04Rik, 0610040J01Rik, 0610043K17Rik, 1010001B22Rik, 1110001J03Rik, 1110002J07Rik, 1110002L01Rik, 1110002O04Rik, 1110004E09Rik, 1110004F10Rik, 1110007C09Rik, 1110008F13Rik, 1110008L16Rik, 1110008P14Rik, 1110012L19Rik, 1110015O18Rik, 1110017D15Rik, 1110018N20Rik, 1110019D14Rik, 1110020A21Rik, 1110025M09Rik, 1110032A03Rik, 1110032F04Rik, 1110034G24Rik, 1110035H17Rik, 1110037F02Rik, 1110038B12Rik, 1110038F14Rik, 1110046J04Rik, 1110051M20Rik, 1110059E24Rik, 1110059G10Rik, 1110065P20Rik, 1190002F15Rik, 1190002N15Rik, 1190003K10Rik, 1190005I06Rik, 1190007I07Rik, 1200014J11Rik, 1300002E11Rik, 1500002C15Rik, 1500002F19Rik, 1500004A13Rik, 1500009C09Rik, 1500009L16Rik, 1500011B03Rik, 1500011K16Rik, 1500012F01Rik, 1500012K07Rik, 1500015A07Rik, 1500015L24Rik, 1500015O10Rik, 1500017E21Rik, 1500026H17Rik, 1500035N22Rik, 1520401A03Rik, 1600002H07Rik, 1600002K03Rik, 1600012H06Rik, 1600014C10Rik, 1600014C23Rik, 1600020E01Rik, 1700001C02Rik, 1700001G11Rik, 1700001G17Rik, 1700001J03Rik, 1700001L05Rik, 1700001L19Rik, 1700001O22Rik, 1700001P01Rik, 1700003E16Rik, 1700003F12Rik, 1700003M02Rik, 1700007G11Rik, 1700007K13Rik, 1700007L15Rik, 1700007P06Rik, 1700008J07Rik, 1700008O03Rik, 1700009N14Rik, 1700010I14Rik, 1700010K24Rik, 1700011I03Rik, 1700012B09Rik, 1700013F07Rik, 1700015F17Rik, 1700015G11Rik, ...]

[17919 rows x 0 columns]

In [9]:
ad_sp.X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
# ad_sp.write_h5ad('data/corrected_ad_sp.h5ad')

## Convert single-cell data

In [2]:
# single-cell meta data - cell-type annotation
path = os.path.join('data', 'puck_cell_cluster.txt')
# sc_meta = pd.read_csv(path, 
#                       index_col=0, 
#                       dtype={'cluster':'category', 'subcluster':'category'} 
#                      )
sc_meta = pd.read_csv(path, index_col=0)
sc_meta

                          cluster subcluster      reason
P60CBRep1P1_GACTCTACACCC        4        4-1         NaN
P60CBRep1P1_TATTATATCTAA        2          2    curation
P60CBRep1P1_GCGTCGCCAGTT       10       10-3         NaN
P60CBRep1P1_CTATCGATTTCN        2          2    curation
P60CBRep1P1_GTACCTGAGCCT        4        4-3         NaN
...                           ...        ...         ...
P60CBRep3P2_TATCTTGCTCTG        1          1  small_cell
P60CBRep3P2_ATTCAAGAAGGC        1          1  small_cell
P60CBRep3P2_GTGGCATTTCCA        1          1  small_cell
P60CBRep3P2_GCGCGACACTGC        1          1  small_cell
P60CBRep3P2_CCCTGTTCAAAT        1          1  small_cell

[26139 rows x 3 columns]

In [6]:
celltype_dict = {1:"Granular",
                2:"Purkinje",
                3:"PV Interneurons",
                4:"Other Interneurons",
                5:"Microglia",
                6:"Oligo- Poly-dendrocyte",
                7:"Bergmann Glia",
                8:"Astrocytes",
                9:"Choroid Plexus",
                10:"Endothelial Stalk",
                11:"Muraland Tip"}

sc_meta_named = sc_meta.replace({"cluster": celltype_dict}) 
sc_meta_named

                                     cluster subcluster      reason
P60CBRep1P1_GACTCTACACCC  Other Interneurons        4-1         NaN
P60CBRep1P1_TATTATATCTAA            Purkinje          2    curation
P60CBRep1P1_GCGTCGCCAGTT   Endothelial Stalk       10-3         NaN
P60CBRep1P1_CTATCGATTTCN            Purkinje          2    curation
P60CBRep1P1_GTACCTGAGCCT  Other Interneurons        4-3         NaN
...                                      ...        ...         ...
P60CBRep3P2_TATCTTGCTCTG            Granular          1  small_cell
P60CBRep3P2_ATTCAAGAAGGC            Granular          1  small_cell
P60CBRep3P2_GTGGCATTTCCA            Granular          1  small_cell
P60CBRep3P2_GCGCGACACTGC            Granular          1  small_cell
P60CBRep3P2_CCCTGTTCAAAT            Granular          1  small_cell

[26139 rows x 3 columns]

In [7]:
sc_counts = pd.read_csv('data/puck_dge.txt', index_col=0)
sc_counts

,0610010F05Rik,0610030E20Rik,1110004E09Rik,1110019D14Rik,1110037F02Rik,1110046J04Rik,1110059G10Rik,1190003K10Rik,1200014J11Rik,1300002E11Rik,...,Zmynd11,Zmynd8,Znhit6,Znrd1as,Zranb1,Zranb2,Zrsr1,Zrsr2,Zyg11b,Zzef1
P60CBRep1P1_GACTCTACACCC,1,0,3,0,0,0,0,0,0,0,...,1,0,0,0,0,2,1,1,2,0
P60CBRep1P1_TATTATATCTAA,1,1,0,0,0,0,2,0,2,0,...,2,1,0,0,6,7,4,0,0,3
P60CBRep1P1_GCGTCGCCAGTT,0,0,2,0,1,0,2,0,2,1,...,3,0,0,0,0,1,0,3,2,0
P60CBRep1P1_CTATCGATTTCN,0,0,1,1,1,0,1,0,0,0,...,3,1,0,0,0,6,1,0,0,1
P60CBRep1P1_GTACCTGAGCCT,0,0,3,0,0,1,0,0,1,0,...,2,0,1,0,0,6,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P60CBRep3P2_TATCTTGCTCTG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P60CBRep3P2_ATTCAAGAAGGC,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
P60CBRep3P2_GTGGCATTTCCA,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P60CBRep3P2_GCGCGACACTGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
P60CBRep3P2_CCCTGTTCAAAT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [8]:
# make sure the index are in the same order
assert sc_meta.index.equals(sc_counts.index)

In [9]:
# convert to single-ce;; anndata
ad_sc = sc.AnnData(sc_counts)
ad_sc.obs['cluster'] = sc_meta_named.cluster
ad_sc.obs['subcluster'] = sc_meta_named.subcluster
ad_sc

AnnData object with n_obs Ã— n_vars = 26139 Ã— 2505
    obs: 'cluster', 'subcluster'

In [10]:
ad_sc.obs

                                     cluster subcluster
P60CBRep1P1_GACTCTACACCC  Other Interneurons        4-1
P60CBRep1P1_TATTATATCTAA            Purkinje          2
P60CBRep1P1_GCGTCGCCAGTT   Endothelial Stalk       10-3
P60CBRep1P1_CTATCGATTTCN            Purkinje          2
P60CBRep1P1_GTACCTGAGCCT  Other Interneurons        4-3
...                                      ...        ...
P60CBRep3P2_TATCTTGCTCTG            Granular          1
P60CBRep3P2_ATTCAAGAAGGC            Granular          1
P60CBRep3P2_GTGGCATTTCCA            Granular          1
P60CBRep3P2_GCGCGACACTGC            Granular          1
P60CBRep3P2_CCCTGTTCAAAT            Granular          1

[26139 rows x 2 columns]

In [17]:
ad_sc.var

Empty DataFrame
Columns: []
Index: [0610010F05Rik, 0610030E20Rik, 1110004E09Rik, 1110019D14Rik, 1110037F02Rik, 1110046J04Rik, 1110059G10Rik, 1190003K10Rik, 1200014J11Rik, 1300002E11Rik, 1500002C15Rik, 1500011K16Rik, 1500012F01Rik, 1500015O10Rik, 1700020I14Rik, 1700025G04Rik, 1700028E10Rik, 1700034I23Rik, 2010012O05Rik, 2210016L21Rik, 2210404O09Rik, 2310033P09Rik, 2410089E03Rik, 2510002D24Rik, 2610008E11Rik, 2610015P09Rik, 2610020C07Rik, 2610035F20Rik, 2610037D02Rik, 2700029M09Rik, 2700049A03Rik, 2810004N23Rik, 2810006K23Rik, 2810013P06Rik, 2810405F17Rik, 2810428I15Rik, 2810474O19Rik, 2900011O08Rik, 2900055J20Rik, 3010026O09Rik, 3222401L13Rik, 4632415L05Rik, 4632427E13Rik, 4921524J17Rik, 4930515G01Rik, 4932438A13Rik, 4933427D14Rik, 5330434G04Rik, 5430405H02Rik, 5430416N02Rik, 5530601H04Rik, 5730455P16Rik, 5830416P10Rik, 5830428H23Rik, 6030442K20Rik, 6330408A02Rik, 6430573F11Rik, 6430590A07Rik, 6720427I07Rik, 8430408G22Rik, 9030624J02Rik, 9230114K14Rik, 9330159F19Rik, 9430020K01Rik, 9530034E10Rik, 9930021J03Rik, A130014A01Rik, A430033K04Rik, A430035B10Rik, A830010M20Rik, A830018L16Rik, A830082K12Rik, AF529169, AI314180, AI987944, AU019823, AW047730, Abcb1a, Abcc9, Abcd2, Abcf1, Abcg2, Abl2, Ablim1, Acat1, Acbd3, Acbd5, Ace2, Acin1, Acsbg1, Acsl3, Acta1, Acta2, Actb, Actr6, Acvr1c, Adamts18, Adamtsl1, Adarb1, Adcy1, ...]

[2505 rows x 0 columns]

In [18]:
ad_sc.X

array([[1., 0., 3., ..., 1., 2., 0.],
       [1., 1., 0., ..., 0., 0., 3.],
       [0., 0., 2., ..., 3., 2., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [5]:
# metacell_dict = {'1':"Granular",
#                 '2':"Purkinje",
#                 '3':"PV Interneurons",
#                 '4':"Other Interneurons",
#                 '5':"Microglia",
#                 '6':"Oligo- Poly-dendrocyte",
#                 '7':"Bergmann Glia",
#                 '8':"Astrocytes",
#                 '9':"Choroid Plexus",
#                 '10':"Endothelial Stalk",
#                 '11':"Muraland Tip"}

# celltype_dict = {1:"Granular",
#                 2:"Purkinje",
#                 3:"PV Interneurons",
#                 4:"Other Interneurons",
#                 5:"Microglia",
#                 6:"Oligo- Poly-dendrocyte",
#                 7:"Bergmann Glia",
#                 8:"Astrocytes",
#                 9:"Choroid Plexus",
#                 10:"Endothelial Stalk",
#                 11:"Muraland Tip"}

In [11]:
# ad_sc.write_h5ad('data/corrected_ad_sc.h5ad')

/home/myp2113/miniconda3/lib/python3.8/site-packages/anndata/_core/anndata.py:1192: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  if is_string_dtype(df[key]) and not is_categorical(df[key])
... storing 'cluster' as categorical
... storing 'subcluster' as categorical