In [24]:
import os, sys
import scipy.io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scanpy as sc

In [25]:
# original data with all the information: spatial, classification, and marker genes
# data is from https://datadryad.org/stash/dataset/doi:10.5061/dryad.8t8s248
path = os.path.join('data', 'GSE113576_spatial_classification_marker.csv')
sp = pd.read_csv(path, index_col=0)
sp

,Animal_ID,Animal_sex,Behavior,Bregma,Centroid_X,Centroid_Y,Cell_class,Neuron_cluster_ID,Ace2,Adora2a,...,Penk,Scg2,Sln,Sst,Tac1,Tac2,Th,Trh,Ucn3,Vgf
Cell_ID,,,,,,,,,,,,,,,,,,,,,
6749ccb4-2ed1-4029-968f-820a287f43c8,1,Female,Naive,0.26,-3211.562145,2608.541476,Astrocyte,NaN,0.0,1.638275,...,0.133016,0.000000,0.865263,0.002977,0.054826,0.008934,0.000000,0.000000,0.000000,0.000000
6cac74bd-4ea7-4701-8701-42563cc65eb8,1,Female,Naive,0.26,-3207.923151,2621.795437,Inhibitory,I-5,0.0,0.000000,...,0.000000,0.000000,0.277939,0.868702,0.580957,0.010079,0.000000,0.000000,0.000000,0.000000
9f29bd57-16a5-4b26-b9f5-37598809da9e,1,Female,Naive,0.26,-3209.578004,2633.153494,Inhibitory,I-6,0.0,0.000000,...,0.213939,0.000000,0.377907,0.049332,0.084898,0.008951,0.000000,0.000000,0.000000,0.000000
d7eb4e0b-276e-47e3-a55c-0b033180a2fe,1,Female,Naive,0.26,-3203.853515,2756.045983,Inhibitory,I-5,0.0,0.000000,...,0.050882,0.089038,0.000000,0.000000,0.001530,0.031364,0.000000,0.000000,0.000000,0.001138
54434f3a-eba9-4aec-af35-c9d317ffa1d5,1,Female,Naive,0.26,-3202.682705,2608.803635,Inhibitory,I-9,0.0,0.000000,...,1.250661,0.159618,0.211159,0.000000,0.087730,0.000000,0.000000,0.000000,0.000000,0.029419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eaaf93ba-75b1-40cd-af08-a4d803511354,30,Male,Mating,0.11,2732.438894,-2322.578167,Ambiguous,NaN,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.040998,0.000000,0.000000,0.024618,0.000000
bb9caf59-d960-452e-a9fd-9238ce5e44ca,30,Male,Mating,0.11,2732.665807,-2120.226450,Ambiguous,NaN,0.0,0.000000,...,0.000000,0.852081,0.000000,0.695548,0.000000,0.024392,0.475944,0.000000,0.000000,0.000000
2f45d61d-3a80-470b-8cb8-251a2c8d2e59,30,Male,Mating,0.11,2826.247461,-2308.947366,Ambiguous,NaN,0.0,0.000000,...,0.058011,0.000000,0.000000,0.000000,0.000000,0.061898,0.000000,0.000000,0.000000,0.000000
180ae0ff-9817-48b9-8d34-b374bda6e316,30,Male,Mating,0.11,2900.963778,-2174.600160,Inhibitory,I-2,0.0,0.000000,...,0.000000,0.326172,0.000000,0.000000,0.000000,0.063518,0.000000,0.000000,0.000000,0.000000
83463d3a-29c5-40c3-b762-ffc3b7a11ad3,30,Male,Mating,0.11,2817.020857,-1716.243777,Ambiguous,NaN,0.0,0.000000,...,0.000000,0.000000,0.000000,0.026406,0.007543,0.069503,0.000000,0.026432,0.000000,0.000000

In [26]:
sp.Cell_class.unique()

array(['Astrocyte', 'Inhibitory', 'OD Mature 2', 'Endothelial 1',
       'Ambiguous', 'Pericytes', 'Endothelial 2', 'OD Mature 1',
       'OD Immature 1', 'Excitatory', 'Microglia', 'Endothelial 3',
       'OD Mature 4', 'OD Immature 2', 'OD Mature 3', 'Ependymal'],
      dtype=object)

In [10]:
# single-cell data
# data is from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE113576

path = os.path.join('data', 'GSE113576_barcodes.tsv.gz')
sc_barcodes = pd.read_csv(path, 
                          compression='gzip', 
                          header=None, 
                          names=['barcodes'],
                          index_col=0)
sc_barcodes

Empty DataFrame
Columns: []
Index: [AAACCTGAGATGTGGC-1, AAACCTGCACACAGAG-1, AAACCTGCACTACAGT-1, AAACCTGTCAGGATCT-1, AAACCTGTCGCACTCT-1, AAACGGGAGAACAATC-1, AAACGGGCAAAGGAAG-1, AAACGGGCACAGGTTT-1, AAACGGGCAGGGTATG-1, AAACGGGCAGTATAAG-1, AAACGGGCATGGTCAT-1, AAACGGGGTATGCTTG-1, AAACGGGGTTGCGCAC-1, AAACGGGTCGCTAGCG-1, AAAGATGAGAGGTTAT-1, AAAGATGCAACACCCG-1, AAAGATGCACTGTTAG-1, AAAGATGCATAGAAAC-1, AAAGATGGTAATCACC-1, AAAGATGGTCGAGATG-1, AAAGATGGTCTAAACC-1, AAAGATGGTTCAGGCC-1, AAAGATGTCACGCATA-1, AAAGATGTCATAGCAC-1, AAAGCAAAGGCCCTTG-1, AAAGCAAAGGGCTCTC-1, AAAGCAACATACGCCG-1, AAAGCAAGTAGATTAG-1, AAAGCAAGTATATCCG-1, AAAGCAAGTATGAATG-1, AAAGCAAGTTGGTAAA-1, AAAGCAATCACTGGGC-1, AAAGCAATCTTTCCTC-1, AAAGTAGAGAAACGCC-1, AAAGTAGAGACGCAAC-1, AAAGTAGAGGGCTTCC-1, AAAGTAGCAGTATGCT-1, AAAGTAGGTAAATGAC-1, AAAGTAGGTCTCTCTG-1, AAAGTAGGTGAGCGAT-1, AAAGTAGGTTTGTTTC-1, AAAGTAGTCAGAAATG-1, AAAGTAGTCCCGGATG-1, AAAGTAGTCGGAGGTA-1, AAAGTAGTCGTACCGG-1, AAAGTAGTCTGCAAGT-1, AAAGTAGTCTTAACCT-1, AAATGCCAGCTCAACT-1, AAATGCCAGGCAAAGA-1, AAATGCCAGGTGGGTT-1, AAATGCCAGTATCGAA-1, AAATGCCAGTTGCAGG-1, AAATGCCCAAGACACG-1, AAATGCCCAATGTAAG-1, AAATGCCCAGACAAAT-1, AAATGCCCATGCAACT-1, AAATGCCGTCGGCTCA-1, AAATGCCGTTGATTCG-1, AAATGCCTCGTCTGAA-1, AACACGTAGGAATCGC-1, AACACGTAGTAATCCC-1, AACACGTAGTGGGTTG-1, AACACGTCACGGATAG-1, AACACGTCAGCCTATA-1, AACACGTGTGTTGAGG-1, AACACGTTCAAGGTAA-1, AACACGTTCCAAATGC-1, AACACGTTCTGAGTGT-1, AACACGTTCTTGAGAC-1, AACCATGAGAAACGCC-1, AACCATGAGACTGGGT-1, AACCATGAGATCACGG-1, AACCATGAGATCGGGT-1, AACCATGAGCCGATTT-1, AACCATGAGTAGATGT-1, AACCATGAGTCCTCCT-1, AACCATGCAAATCCGT-1, AACCATGCAAGGTTCT-1, AACCATGCAATGAAAC-1, AACCATGCACCAGCAC-1, AACCATGGTCGCGTGT-1, AACCGCGAGGGCTCTC-1, AACCGCGCACCTGGTG-1, AACCGCGCATCACGAT-1, AACCGCGGTCAAAGAT-1, AACCGCGGTTGTACAC-1, AACCGCGGTTTCCACC-1, AACGTTGAGCCATCGC-1, AACGTTGAGCTGTCTA-1, AACGTTGCAAGAGTCG-1, AACGTTGCAGCTGTGC-1, AACGTTGCATGACATC-1, AACGTTGCATTGAGCT-1, AACGTTGGTACTTGAC-1, AACGTTGGTATAAACG-1, AACGTTGGTCAACTGT-1, AACGTTGTCACTCTTA-1, AACGTTGTCAGGCAAG-1, AACGTTGTCGGCGCAT-1, AACTCAGAGCGAGAAA-1, ...]

[31299 rows x 0 columns]

In [11]:
path = os.path.join('data', 'GSE113576_genes.tsv.gz')
sc_genes = pd.read_csv(path, 
                      compression='gzip', 
                      header=None, 
                      names=['genes'],
                      index_col=0)
sc_genes

Empty DataFrame
Columns: []
Index: [ENSMUSG00000051951	Xkr4, ENSMUSG00000089699	Gm1992, ENSMUSG00000102343	Gm37381, ENSMUSG00000025900	Rp1, ENSMUSG00000109048	Rp1, ENSMUSG00000025902	Sox17, ENSMUSG00000104328	Gm37323, ENSMUSG00000033845	Mrpl15, ENSMUSG00000025903	Lypla1, ENSMUSG00000104217	Gm37988, ENSMUSG00000033813	Tcea1, ENSMUSG00000002459	Rgs20, ENSMUSG00000085623	Gm16041, ENSMUSG00000033793	Atp6v1h, ENSMUSG00000025905	Oprk1, ENSMUSG00000033774	Npbwr1, ENSMUSG00000025907	Rb1cc1, ENSMUSG00000090031	4732440D04Rik, ENSMUSG00000087247	Fam150a, ENSMUSG00000033740	St18, ENSMUSG00000051285	Pcmtd1, ENSMUSG00000097797	Gm26901, ENSMUSG00000103067	Gm30414, ENSMUSG00000025909	Sntg1, ENSMUSG00000061024	Rrs1, ENSMUSG00000025911	Adhfe1, ENSMUSG00000067879	3110035E14Rik, ENSMUSG00000099827	Gm29520, ENSMUSG00000025912	Mybl1, ENSMUSG00000045210	Vcpip1, ENSMUSG00000097893	1700034P13Rik, ENSMUSG00000025915	Sgk3, ENSMUSG00000046101	Mcmdc2, ENSMUSG00000098234	Snhg6, ENSMUSG00000099032	Tcf24, ENSMUSG00000025916	Ppp1r42, ENSMUSG00000087199	Gm15818, ENSMUSG00000025917	Cops5, ENSMUSG00000056763	Cspp1, ENSMUSG00000067851	Arfgef1, ENSMUSG00000042501	Cpa6, ENSMUSG00000048960	Prex2, ENSMUSG00000057715	A830018L16Rik, ENSMUSG00000097171	Gm17644, ENSMUSG00000101314	Gm29663, ENSMUSG00000016918	Sulf1, ENSMUSG00000025938	Slco5a1, ENSMUSG00000099498	Gm29283, ENSMUSG00000042414	Prdm14, ENSMUSG00000005886	Ncoa2, ENSMUSG00000101476	Gm29570, ENSMUSG00000025935	Tram1, ENSMUSG00000025937	Lactb2, ENSMUSG00000067813	Xkr9, ENSMUSG00000025932	Eya1, ENSMUSG00000054493	Gm9947, ENSMUSG00000025930	Msc, ENSMUSG00000032769	Trpa1, ENSMUSG00000092083	Kcnb2, ENSMUSG00000025925	Terf1, ENSMUSG00000032719	Sbspon, ENSMUSG00000067795	4930444P10Rik, ENSMUSG00000043716	Rpl7, ENSMUSG00000025921	Rdh10, ENSMUSG00000100868	Gm28095, ENSMUSG00000025920	Stau2, ENSMUSG00000089982	Gm7568, ENSMUSG00000025939	Ube2w, ENSMUSG00000079658	Tceb1, ENSMUSG00000097744	D030040B21Rik, ENSMUSG00000025940	Tmem70, ENSMUSG00000025779	Ly96, ENSMUSG00000101640	Gm28376, ENSMUSG00000042686	Jph1, ENSMUSG00000100110	Gm28783, ENSMUSG00000025777	Gdap1, ENSMUSG00000099899	Gm28784, ENSMUSG00000067780	Pi15, ENSMUSG00000100053	Gm28154, ENSMUSG00000085125	Gm16070, ENSMUSG00000025776	Crispld1, ENSMUSG00000099895	Gm28153, ENSMUSG00000025774	Crisp4, ENSMUSG00000073735	Defb18, ENSMUSG00000067773	Defb41, ENSMUSG00000101738	Gm29006, ENSMUSG00000089787	Gm15825, ENSMUSG00000042596	Tfap2d, ENSMUSG00000025927	Tfap2b, ENSMUSG00000100538	Gm28340, ENSMUSG00000043760	Pkhd1, ENSMUSG00000089914	4930486I03Rik, ENSMUSG00000099906	Gm28653, ENSMUSG00000025929	Il17a, ENSMUSG00000041872	Il17f, ENSMUSG00000041859	Mcm3, ENSMUSG00000102121	Gm28065, ENSMUSG00000097934	6720483E21Rik, ENSMUSG00000025931	Paqr8, ENSMUSG00000041809	Efhc1, ...]

[27998 rows x 0 columns]

In [17]:
path = os.path.join('data', 'GSE113576_matrix.mtx.gz')
sc_mtx = scipy.io.mmread(path)
sc_mtx = sc_mtx.todense()
sc_mtx

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [18]:
sc_mtx.shape

(27998, 31299)

In [19]:
ad_sc = sc.AnnData(sc_mtx.transpose(), 
                   obs=sc_barcodes, 
                   var=sc_genes)
ad_sc

AnnData object with n_obs × n_vars = 31299 × 27998

In [20]:
ad_sc.obs

Empty DataFrame
Columns: []
Index: [AAACCTGAGATGTGGC-1, AAACCTGCACACAGAG-1, AAACCTGCACTACAGT-1, AAACCTGTCAGGATCT-1, AAACCTGTCGCACTCT-1, AAACGGGAGAACAATC-1, AAACGGGCAAAGGAAG-1, AAACGGGCACAGGTTT-1, AAACGGGCAGGGTATG-1, AAACGGGCAGTATAAG-1, AAACGGGCATGGTCAT-1, AAACGGGGTATGCTTG-1, AAACGGGGTTGCGCAC-1, AAACGGGTCGCTAGCG-1, AAAGATGAGAGGTTAT-1, AAAGATGCAACACCCG-1, AAAGATGCACTGTTAG-1, AAAGATGCATAGAAAC-1, AAAGATGGTAATCACC-1, AAAGATGGTCGAGATG-1, AAAGATGGTCTAAACC-1, AAAGATGGTTCAGGCC-1, AAAGATGTCACGCATA-1, AAAGATGTCATAGCAC-1, AAAGCAAAGGCCCTTG-1, AAAGCAAAGGGCTCTC-1, AAAGCAACATACGCCG-1, AAAGCAAGTAGATTAG-1, AAAGCAAGTATATCCG-1, AAAGCAAGTATGAATG-1, AAAGCAAGTTGGTAAA-1, AAAGCAATCACTGGGC-1, AAAGCAATCTTTCCTC-1, AAAGTAGAGAAACGCC-1, AAAGTAGAGACGCAAC-1, AAAGTAGAGGGCTTCC-1, AAAGTAGCAGTATGCT-1, AAAGTAGGTAAATGAC-1, AAAGTAGGTCTCTCTG-1, AAAGTAGGTGAGCGAT-1, AAAGTAGGTTTGTTTC-1, AAAGTAGTCAGAAATG-1, AAAGTAGTCCCGGATG-1, AAAGTAGTCGGAGGTA-1, AAAGTAGTCGTACCGG-1, AAAGTAGTCTGCAAGT-1, AAAGTAGTCTTAACCT-1, AAATGCCAGCTCAACT-1, AAATGCCAGGCAAAGA-1, AAATGCCAGGTGGGTT-1, AAATGCCAGTATCGAA-1, AAATGCCAGTTGCAGG-1, AAATGCCCAAGACACG-1, AAATGCCCAATGTAAG-1, AAATGCCCAGACAAAT-1, AAATGCCCATGCAACT-1, AAATGCCGTCGGCTCA-1, AAATGCCGTTGATTCG-1, AAATGCCTCGTCTGAA-1, AACACGTAGGAATCGC-1, AACACGTAGTAATCCC-1, AACACGTAGTGGGTTG-1, AACACGTCACGGATAG-1, AACACGTCAGCCTATA-1, AACACGTGTGTTGAGG-1, AACACGTTCAAGGTAA-1, AACACGTTCCAAATGC-1, AACACGTTCTGAGTGT-1, AACACGTTCTTGAGAC-1, AACCATGAGAAACGCC-1, AACCATGAGACTGGGT-1, AACCATGAGATCACGG-1, AACCATGAGATCGGGT-1, AACCATGAGCCGATTT-1, AACCATGAGTAGATGT-1, AACCATGAGTCCTCCT-1, AACCATGCAAATCCGT-1, AACCATGCAAGGTTCT-1, AACCATGCAATGAAAC-1, AACCATGCACCAGCAC-1, AACCATGGTCGCGTGT-1, AACCGCGAGGGCTCTC-1, AACCGCGCACCTGGTG-1, AACCGCGCATCACGAT-1, AACCGCGGTCAAAGAT-1, AACCGCGGTTGTACAC-1, AACCGCGGTTTCCACC-1, AACGTTGAGCCATCGC-1, AACGTTGAGCTGTCTA-1, AACGTTGCAAGAGTCG-1, AACGTTGCAGCTGTGC-1, AACGTTGCATGACATC-1, AACGTTGCATTGAGCT-1, AACGTTGGTACTTGAC-1, AACGTTGGTATAAACG-1, AACGTTGGTCAACTGT-1, AACGTTGTCACTCTTA-1, AACGTTGTCAGGCAAG-1, AACGTTGTCGGCGCAT-1, AACTCAGAGCGAGAAA-1, ...]

[31299 rows x 0 columns]

In [21]:
ad_sc.var

Empty DataFrame
Columns: []
Index: [ENSMUSG00000051951	Xkr4, ENSMUSG00000089699	Gm1992, ENSMUSG00000102343	Gm37381, ENSMUSG00000025900	Rp1, ENSMUSG00000109048	Rp1, ENSMUSG00000025902	Sox17, ENSMUSG00000104328	Gm37323, ENSMUSG00000033845	Mrpl15, ENSMUSG00000025903	Lypla1, ENSMUSG00000104217	Gm37988, ENSMUSG00000033813	Tcea1, ENSMUSG00000002459	Rgs20, ENSMUSG00000085623	Gm16041, ENSMUSG00000033793	Atp6v1h, ENSMUSG00000025905	Oprk1, ENSMUSG00000033774	Npbwr1, ENSMUSG00000025907	Rb1cc1, ENSMUSG00000090031	4732440D04Rik, ENSMUSG00000087247	Fam150a, ENSMUSG00000033740	St18, ENSMUSG00000051285	Pcmtd1, ENSMUSG00000097797	Gm26901, ENSMUSG00000103067	Gm30414, ENSMUSG00000025909	Sntg1, ENSMUSG00000061024	Rrs1, ENSMUSG00000025911	Adhfe1, ENSMUSG00000067879	3110035E14Rik, ENSMUSG00000099827	Gm29520, ENSMUSG00000025912	Mybl1, ENSMUSG00000045210	Vcpip1, ENSMUSG00000097893	1700034P13Rik, ENSMUSG00000025915	Sgk3, ENSMUSG00000046101	Mcmdc2, ENSMUSG00000098234	Snhg6, ENSMUSG00000099032	Tcf24, ENSMUSG00000025916	Ppp1r42, ENSMUSG00000087199	Gm15818, ENSMUSG00000025917	Cops5, ENSMUSG00000056763	Cspp1, ENSMUSG00000067851	Arfgef1, ENSMUSG00000042501	Cpa6, ENSMUSG00000048960	Prex2, ENSMUSG00000057715	A830018L16Rik, ENSMUSG00000097171	Gm17644, ENSMUSG00000101314	Gm29663, ENSMUSG00000016918	Sulf1, ENSMUSG00000025938	Slco5a1, ENSMUSG00000099498	Gm29283, ENSMUSG00000042414	Prdm14, ENSMUSG00000005886	Ncoa2, ENSMUSG00000101476	Gm29570, ENSMUSG00000025935	Tram1, ENSMUSG00000025937	Lactb2, ENSMUSG00000067813	Xkr9, ENSMUSG00000025932	Eya1, ENSMUSG00000054493	Gm9947, ENSMUSG00000025930	Msc, ENSMUSG00000032769	Trpa1, ENSMUSG00000092083	Kcnb2, ENSMUSG00000025925	Terf1, ENSMUSG00000032719	Sbspon, ENSMUSG00000067795	4930444P10Rik, ENSMUSG00000043716	Rpl7, ENSMUSG00000025921	Rdh10, ENSMUSG00000100868	Gm28095, ENSMUSG00000025920	Stau2, ENSMUSG00000089982	Gm7568, ENSMUSG00000025939	Ube2w, ENSMUSG00000079658	Tceb1, ENSMUSG00000097744	D030040B21Rik, ENSMUSG00000025940	Tmem70, ENSMUSG00000025779	Ly96, ENSMUSG00000101640	Gm28376, ENSMUSG00000042686	Jph1, ENSMUSG00000100110	Gm28783, ENSMUSG00000025777	Gdap1, ENSMUSG00000099899	Gm28784, ENSMUSG00000067780	Pi15, ENSMUSG00000100053	Gm28154, ENSMUSG00000085125	Gm16070, ENSMUSG00000025776	Crispld1, ENSMUSG00000099895	Gm28153, ENSMUSG00000025774	Crisp4, ENSMUSG00000073735	Defb18, ENSMUSG00000067773	Defb41, ENSMUSG00000101738	Gm29006, ENSMUSG00000089787	Gm15825, ENSMUSG00000042596	Tfap2d, ENSMUSG00000025927	Tfap2b, ENSMUSG00000100538	Gm28340, ENSMUSG00000043760	Pkhd1, ENSMUSG00000089914	4930486I03Rik, ENSMUSG00000099906	Gm28653, ENSMUSG00000025929	Il17a, ENSMUSG00000041872	Il17f, ENSMUSG00000041859	Mcm3, ENSMUSG00000102121	Gm28065, ENSMUSG00000097934	6720483E21Rik, ENSMUSG00000025931	Paqr8, ENSMUSG00000041809	Efhc1, ...]

[27998 rows x 0 columns]

In [22]:
ad_sc.X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [27]:
# ad_sc.write_h5ad('data/GSE113576_sc.h5ad')